--Adding Directory
CREATE OR REPLACE DIRECTORY imp_data AS 'C:\PLSQL\data';

--Adding permissions
GRANT READ, WRITE ON DIRECTORY imp_data TO PUBLIC;

--Creating table for import data
CREATE TABLE imp_data (
  ID NUMBER(20),
  BEGIN_DATE DATE,
  FIRST_NAME VARCHAR2(30),
  LAST_NAME VARCHAR2(30),
  STATUS VARCHAR2(20)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY imp_data
  ACCESS PARAMETERS
    (
	RECORDS DELIMITED BY NEWLINE
    BADFILE 'bad'
    LOGFILE 'log'
    FIELDS TERMINATED BY ','
    (ID, BEGIN_DATE, FIRST_NAME, LAST_NAME, STATUS)
	)
  LOCATION ('sample.csv')
)
 PARALLEL 5
 REJECT LIMIT UNLIMITED;
